### ISSUE TITLE
Your algorithm is ambigous

### ISSUE THREAD

**Issue by dvberkel** [HAN-ASD-DT/sorting-assignment-titusvh#2]
I get the gist of your algorithm, but is is not very precise. For example, where do `item1` and `item2` come from.

Could you make the algorithm more precise?

**Comment by titusvh** [comment]
You caught me with version alpha 0.01 which I slammed together few minutes before the deadline last thursday, because the time we spent talking in the lesson. Will create an implementation this week.

**Comment by dvberkel** [comment]
Note that there is no deadline ;-)

And although an implementation is not necessary, it helps with the precision

**Comment by titusvh** [comment]
I understood that. But I need it for myself. And possibly this is a nice exercise to sharpen the saw concerning TDD. Also I hate lessons where stuff is explained before I got the chance to fool around with myself. So I can be sure my understanding and solutions were found independent and did not grow from seeds planted by others. (Sometimes I actually shut down an online lesson for that reason...) For the sorting this won't be an issue, but for Turing it is. So I hope to find a time gap to finish the exercise before the meeting tonight. (supplying dinner to one's kids is sooo overrated ;-)

**Comment by titusvh** [comment]
Fixed the unclarities.

**Comment by dvberkel** [comment]
> Also I hate lessons where stuff is explained before I got the chance to fool around with myself. So I can be sure my understanding and solutions were found independent and did not grow from seeds planted by others.

I was planning on discussing one of the Turing Machine assignments. But I will ask before hand if that is to soon.

**Comment by dvberkel** [comment]
> Fixed the unclarities.

I still think there is some ambiguities, but implementing will drive them out

**Comment by titusvh** [comment]
>I was planning on discussing one of the Turing Machine assignments. But I will ask before hand if that is to soon.

No @dvberkel , I think the time available was fine. It was my personal failure to spend time.
However, I just spent my lunch break and finished the Turing Palindrome assignment.

**Comment by titusvh** [comment]
> I still think there is some ambiguities, but implementing will drive them out
Please elaborate. Apparently I was not able to see this as an outsider would.
